#!/bin/bash

# read rules from stdin
rules=$( cat )

# rules ?
[ ! "${rules}" ] &&
    echo 'no data !' > /dev/stderr &&
        exit 1

# bad rules ?
grep -qv '^-P INPUT' <( head -1 <<< "${rules}" ) &&
    echo 'bad data ! (use iptables -S as input)' > /dev/stderr &&
        exit 2

# iptables chains
chains="INPUT FORWARD OUTPUT"
for chain in ${chains}
do
    echo ${chain}:
    # get links of the current chain
    links=$( egrep "\<${chain}\>" <<< "${rules}" )
    # remove first line (policy) and "append" statment
    sed -e 1d -e "s/^-A ${chain} //g" <<< "${links}"
    # end with policy
    head -1 <<< "${links}"
    echo
done

# user chains
chains=$( awk '/^-N [^ ]+$/{print $2}' <<< "${rules}" )
if [ "${chains}" ]
then
    for chain in ${chains}
    do
        echo ${chain}:
        # get links of the current user chain
        links=$( egrep "^-A \<${chain}\>" <<< "${rules}" )
        # remove "append" statment
        sed "s/^-A ${chain} //g" <<< "${links}"
        echo
    done
fi
